version: '2'
services: 
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
  web:
    build: .
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
