CREATE SCHEMA IF NOT EXISTS ed_platform;

CREATE TABLE IF NOT EXISTS users (
	id         SERIAL NOT NULL PRIMARY KEY,
	email      VARCHAR(120) NOT NULL UNIQUE,
	password   VARCHAR(255) NOT NULL,
	first_name VARCHAR(255),
	last_name  VARCHAR(255),
	created_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
	id                SERIAL NOT NULL PRIMARY KEY,
	title             VARCHAR(120) NOT NULL UNIQUE,
	description       TEXT,
	author_id         INT NOT NULL REFERENCES users,
	created_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users_courses (
	user_id   INT NOT NULL REFERENCES users,
	cource_id INT NOT NULL REFERENCES courses
);